git:
  quiet: true

service:
  - docker

language: csharp
mono: none
dotnet: 3.1.201

install:
  - git checkout $TRAVIS_BRANCH
  - docker pull gittools/gitversion:5.2.5-linux

before_script:
  - export GitVersion_NuGetVersionV2=$(docker run --rm -v "$(pwd):/repo" gittools/gitversion:5.2.5-linux /repo -output json -showvariable NuGetVersionV2)
  - echo "Nuget package version is $GitVersion_NuGetVersionV2"

script:
  - dotnet pack
