git:
  depth: 1
  quiet: true

language: csharp
mono: none
dotnet: 3.1.201

install:
  - gem install gitversion

script:
  - chmod +x ./build/build_package.sh
  - ./build/build_package.sh

